const PLANTS = [
  { id: 'tomato',      name: 'Tomato',       emoji: '🍅', perSqFt: 1,  color: '#e74c3c', category: 'Fruiting' },
  { id: 'pepper',      name: 'Pepper',       emoji: '🫑', perSqFt: 1,  color: '#c0392b', category: 'Fruiting' },
  { id: 'eggplant',    name: 'Eggplant',     emoji: '🍆', perSqFt: 1,  color: '#8e44ad', category: 'Fruiting' },
  { id: 'zucchini',    name: 'Zucchini',     emoji: '🥒', perSqFt: 1,  color: '#27ae60', category: 'Fruiting' },
  { id: 'cucumber',    name: 'Cucumber',     emoji: '🥒', perSqFt: 2,  color: '#2ecc71', category: 'Fruiting' },
  { id: 'strawberry',  name: 'Strawberry',   emoji: '🍓', perSqFt: 4,  color: '#e74c3c', category: 'Fruiting' },
  { id: 'pumpkin',     name: 'Pumpkin',      emoji: '🎃', perSqFt: 1,  color: '#e67e22', category: 'Fruiting' },
  { id: 'broccoli',    name: 'Broccoli',     emoji: '🥦', perSqFt: 1,  color: '#27ae60', category: 'Brassica' },
  { id: 'cabbage',     name: 'Cabbage',      emoji: '🥬', perSqFt: 1,  color: '#1abc9c', category: 'Brassica' },
  { id: 'cauliflower', name: 'Cauliflower',  emoji: '🥦', perSqFt: 1,  color: '#ecf0f1', category: 'Brassica' },
  { id: 'kale',        name: 'Kale',         emoji: '🥬', perSqFt: 2,  color: '#16a085', category: 'Brassica' },
  { id: 'lettuce_head', name: 'Head Lettuce',   emoji: '🥬', perSqFt: 1,  color: '#27ae60', category: 'Greens' },
  { id: 'lettuce_leaf', name: 'Leaf Lettuce',   emoji: '🥗', perSqFt: 4,  color: '#2ecc71', category: 'Greens' },
  { id: 'mesclun',      name: 'Mesclun Mix',    emoji: '🌿', perSqFt: 9,  color: '#1abc9c', category: 'Greens' },
  { id: 'spinach',     name: 'Spinach',      emoji: '🌿', perSqFt: 9,  color: '#27ae60', category: 'Greens' },
  { id: 'swiss_chard', name: 'Swiss Chard',  emoji: '🌱', perSqFt: 4,  color: '#1abc9c', category: 'Greens' },
  { id: 'arugula',     name: 'Arugula',      emoji: '🌿', perSqFt: 4,  color: '#2ecc71', category: 'Greens' },
  { id: 'carrot',      name: 'Carrot',       emoji: '🥕', perSqFt: 16, color: '#e67e22', category: 'Root' },
  { id: 'radish',      name: 'Radish',       emoji: '🔴', perSqFt: 16, color: '#e74c3c', category: 'Root' },
  { id: 'beet',        name: 'Beet',         emoji: '🟣', perSqFt: 9,  color: '#8e44ad', category: 'Root' },
  { id: 'turnip',      name: 'Turnip',       emoji: '⚪', perSqFt: 9,  color: '#95a5a6', category: 'Root' },
  { id: 'onion',       name: 'Onion',        emoji: '🧅', perSqFt: 16, color: '#f39c12', category: 'Allium' },
  { id: 'garlic',      name: 'Garlic',       emoji: '🧄', perSqFt: 9,  color: '#f1c40f', category: 'Allium' },
  { id: 'leek',        name: 'Leek',         emoji: '🌿', perSqFt: 9,  color: '#27ae60', category: 'Allium' },
  { id: 'peas',        name: 'Peas',         emoji: '🫛', perSqFt: 8,  color: '#2ecc71', category: 'Legume' },
  { id: 'bush_beans',  name: 'Bush Beans',   emoji: '🫘', perSqFt: 9,  color: '#27ae60', category: 'Legume' },
  { id: 'pole_beans',  name: 'Pole Beans',   emoji: '🫘', perSqFt: 8,  color: '#1abc9c', category: 'Legume' },
  { id: 'basil',       name: 'Basil',        emoji: '🌿', perSqFt: 4,  color: '#27ae60', category: 'Herb' },
  { id: 'parsley',     name: 'Parsley',      emoji: '🌿', perSqFt: 3,  color: '#2ecc71', category: 'Herb' },
  { id: 'cilantro',    name: 'Cilantro',     emoji: '🌿', perSqFt: 9,  color: '#16a085', category: 'Herb' },
  { id: 'dill',        name: 'Dill',         emoji: '🌿', perSqFt: 4,  color: '#27ae60', category: 'Herb' },
  { id: 'chives',      name: 'Chives',       emoji: '🌿', perSqFt: 16, color: '#2ecc71', category: 'Herb' },
  { id: 'thyme',       name: 'Thyme',        emoji: '🌿', perSqFt: 4,  color: '#1abc9c', category: 'Herb' },
  { id: 'rosemary',    name: 'Rosemary',     emoji: '🌿', perSqFt: 1,  color: '#16a085', category: 'Herb' },
  { id: 'mint',        name: 'Mint',         emoji: '🌿', perSqFt: 4,  color: '#27ae60', category: 'Herb' },
  { id: 'sunflower',   name: 'Sunflower',    emoji: '🌻', perSqFt: 1,  color: '#f1c40f', category: 'Flower' },
  { id: 'marigold',    name: 'Marigold',     emoji: '🌼', perSqFt: 4,  color: '#f39c12', category: 'Flower' },
  { id: 'nasturtium',  name: 'Nasturtium',   emoji: '🌸', perSqFt: 4,  color: '#e74c3c', category: 'Flower' },
  { id: 'lavender',    name: 'Lavender',     emoji: '💜', perSqFt: 1,  color: '#9b59b6', category: 'Flower' },
];

const PLANT_MAP = Object.fromEntries(PLANTS.map(p => [p.id, p]));

const CATEGORIES = [...new Set(PLANTS.map(p => p.category))];
